const plants = [
  {
    "author": "Teas",
    "bibliography": "Gard. Monthly & Hort. Advertiser 17: 181 (1875)",
    "common_name": "Northern catalpa",
    "family": "Bignoniaceae",
    "family_common_name": null,
    "genus": "Catalpa",
    "genus_id": 10217,
    "id": 209793,
    "image_url": "https://bs.plantnet.org/image/o/78388e05f5ab1cd81e59527589973efc9af5da8a",
    "links": {
      "genus": "/api/v1/genus/catalpa",
      "plant": "/api/v1/plants/catalpa-speciosa",
      "self": "/api/v1/species/catalpa-speciosa"
    },
    "rank": "species",
    "scientific_name": "Catalpa speciosa",
    "slug": "catalpa-speciosa",
    "status": "accepted",
    "synonyms": [
      "Catalpa cordifolia",
      "Catalpa bignonioides var. speciosa"
    ],
    "year": 1875
  },
  {
    "author": "G.Don",
    "bibliography": "Gen. Hist. 4: 230 (1837)",
    "common_name": "Chinese catalpa",
    "family": "Bignoniaceae",
    "family_common_name": null,
    "genus": "Catalpa",
    "genus_id": 10217,
    "id": 209790,
    "image_url": "https://bs.plantnet.org/image/o/2a46d7beeac918d5c0a5f99a222e2198785dd886",
    "links": {
      "genus": "/api/v1/genus/catalpa",
      "plant": "/api/v1/plants/catalpa-ovata",
      "self": "/api/v1/species/catalpa-ovata"
    },
    "rank": "species",
    "scientific_name": "Catalpa ovata",
    "slug": "catalpa-ovata",
    "status": "accepted",
    "synonyms": [
      "Catalpa himalayensis",
      "Catalpa kaempferi",
      "Catalpa bungei",
      "Catalpa bignonioides var. kaempferi",
      "Catalpa nana",
      "Catalpa henryi",
      "Catalpa himalayaca",
      "Catalpa wallichiana",
      "Catalpa ovata f. flavescens",
      "Catalpa ovata var. flavescens"
    ],
    "year": 1837
  },
  {
    "author": "Walter",
    "bibliography": "Fl. Carol.: 64 (1788)",
    "common_name": "Indian-bean",
    "family": "Bignoniaceae",
    "family_common_name": null,
    "genus": "Catalpa",
    "genus_id": 10217,
    "id": 209784,
    "image_url": "https://bs.plantnet.org/image/o/49213bf30bb9eb6f167d0163736bca34f246e68e",
    "links": {
      "genus": "/api/v1/genus/catalpa",
      "plant": "/api/v1/plants/catalpa-bignonioides",
      "self": "/api/v1/species/catalpa-bignonioides"
    },
    "rank": "species",
    "scientific_name": "Catalpa bignonioides",
    "slug": "catalpa-bignonioides",
    "status": "accepted",
    "synonyms": [
      "Catalpa ternifolia",
      "Catalpa tibetica",
      "Catalpa bignonioides var. aurea",
      "Catalpa bignonioides var. koehnei",
      "Catalpa bignonioides f. variegata",
      "Catalpa bignonioides f. koehnei",
      "Catalpa bignonioides var. nana",
      "Catalpa bignonioides f. aurea",
      "Catalpa bignonioides f. nana",
      "Catalpa pumila",
      "Catalpa bignonioides var. variegata",
      "Catalpa syringifolia var. nana",
      "Catalpa syringifolia var. aurea",
      "Bignonia spectabilis",
      "Catalpa bignonioides f. pulverulenta",
      "Catalpa bignonioides var. pulverulenta",
      "Bignonia triloba",
      "Catalpa umbraculifera",
      "Catalpa speciosa var. albovariegata",
      "Catalpa communis",
      "Catalpa catalpa",
      "Catalpa speciosa var. pulverulenta",
      "Catalpa syringifolia var. koehnei",
      "Catalpa arborea",
      "Catalpa syringifolia var. pulverulenta",
      "Catalpa speciosa f. pulverulenta",
      "Catalpa speciosa f. albovariegata",
      "Catalpium amena",
      "Bignonia catalpa"
    ],
    "year": 1788
  },
  {
    "author": "C.A.Mey.",
    "bibliography": "Bull. Sci. Acad. Imp. Sci. Saint-Pétersbourg 2: 51 (1837)",
    "common_name": "Manchurian catalpa",
    "family": "Bignoniaceae",
    "family_common_name": null,
    "genus": "Catalpa",
    "genus_id": 10217,
    "id": 209786,
    "image_url": "https://bs.plantnet.org/image/o/b09c2aeb52c3937e159e5fe7fdb295b1eff0ec9d",
    "links": {
      "genus": "/api/v1/genus/catalpa",
      "plant": "/api/v1/plants/catalpa-bungei",
      "self": "/api/v1/species/catalpa-bungei"
    },
    "rank": "species",
    "scientific_name": "Catalpa bungei",
    "slug": "catalpa-bungei",
    "status": "accepted",
    "synonyms": [
      "Catalpa syringifolia",
      "Catalpa bungei var. heterophylla",
      "Catalpa duclouxii",
      "Catalpa vestita",
      "Catalpa fargesii",
      "Catalpa fargesii f. duclouxii",
      "Catalpa sutchuenensis",
      "Catalpa heterophylla",
      "Catalpa fargesii f. alba",
      "Catalpa bungei var. intermedia"
    ],
    "year": 1837
  },
  {
    "author": "(Jacq.) Dum.Cours.",
    "bibliography": "Bot. Cult. 2: 190 (1802)",
    "common_name": null,
    "family": "Bignoniaceae",
    "family_common_name": null,
    "genus": "Catalpa",
    "genus_id": 10217,
    "id": 209788,
    "image_url": "https://d2seqvvyy3b8p2.cloudfront.net/5324fab9e94f3a1420fc724e503b29bd.jpg",
    "links": {
      "genus": "/api/v1/genus/catalpa",
      "plant": "/api/v1/plants/catalpa-longissima",
      "self": "/api/v1/species/catalpa-longissima"
    },
    "rank": "species",
    "scientific_name": "Catalpa longissima",
    "slug": "catalpa-longissima",
    "status": "accepted",
    "synonyms": [
      "Bignonia longisiliqua",
      "Bignonia quercus",
      "Catalpa longisiliqua",
      "Macrocatalpa longissima",
      "Bignonia pseudoquercus",
      "Bignonia tenuisiliqua"
    ],
    "year": 1802
  },
  {
    "author": "(L.) Mill.",
    "bibliography": "Gard. Dict. ed. 8.: n.° 2 (1768)",
    "common_name": "Chinkapin",
    "family": "Fagaceae",
    "family_common_name": null,
    "genus": "Castanea",
    "genus_id": 10459,
    "id": 216054,
    "image_url": "https://bs.plantnet.org/image/o/4357010433ea815fc4ca08e498a7a1eae8f37239",
    "links": {
      "genus": "/api/v1/genus/castanea",
      "plant": "/api/v1/plants/castanea-pumila",
      "self": "/api/v1/species/castanea-pumila"
    },
    "rank": "species",
    "scientific_name": "Castanea pumila",
    "slug": "castanea-pumila",
    "status": "accepted",
    "synonyms": [
      "Fagus pumila var. serotina",
      "Castanea pumila var. nana",
      "Castanea pumila var. fulva",
      "Castanea floridana var. margaretiae",
      "Castanea ashei",
      "Fagus nana",
      "Castanea nana",
      "Fagus pumila",
      "Castanea margaretiae var. angustifolia",
      "Castanea floridana var. angustifolia",
      "Castanea floridana var. arcuata",
      "Castanea margaretiae var. arcuata",
      "Castanea chincapin",
      "Castanea floridana",
      "Castanea pumila subsp. ashei",
      "Castanea alnifolia",
      "Castanea alnifolia subsp. floridana",
      "Castanea pumila var. margaretiae",
      "Castanea paucispina",
      "Castanea pumila var. ashei",
      "Castanea margaretiae",
      "Castanea alnifolia var. floridana",
      "Castanea alnifolia var. pubescens"
    ],
    "year": 1768
  },
  {
    "author": "(A.Rich.) Ekman ex Urb.",
    "bibliography": "Symb. Antill. 9: 254 (1924)",
    "common_name": null,
    "family": "Bignoniaceae",
    "family_common_name": null,
    "genus": "Catalpa",
    "genus_id": 10217,
    "id": 209789,
    "image_url": "https://d2seqvvyy3b8p2.cloudfront.net/0262d85ede3b03d597d8eb5695e07ea0.jpg",
    "links": {
      "genus": "/api/v1/genus/catalpa",
      "plant": "/api/v1/plants/catalpa-macrocarpa",
      "self": "/api/v1/species/catalpa-macrocarpa"
    },
    "rank": "species",
    "scientific_name": "Catalpa macrocarpa",
    "slug": "catalpa-macrocarpa",
    "status": "accepted",
    "synonyms": [
      "Catalpa punctata subsp. domingensis",
      "Catalpa punctata",
      "Robbia macrocarpa",
      "Catalpa punctata var. pubescens",
      "Catalpa domingensis",
      "Catalpa punctata var. domingensis",
      "Macrocatalpa punctata",
      "Macrocatalpa tomentosa",
      "Catalpa punctata f. urbanii",
      "Catalpa punctata var. lepidota",
      "Catalpa pubescens",
      "Echites macrocarpus",
      "Catalpa obovata"
    ],
    "year": 1924
  },
  {
    "author": "Urb.",
    "bibliography": "Repert. Spec. Nov. Regni Veg. 24: 12 (1927)",
    "common_name": null,
    "family": "Bignoniaceae",
    "family_common_name": null,
    "genus": "Catalpa",
    "genus_id": 10217,
    "id": 209785,
    "image_url": "https://bs.plantnet.org/image/o/cc35f40bee14e70f2a2dc61fa31ce51ed3638754",
    "links": {
      "genus": "/api/v1/genus/catalpa",
      "plant": "/api/v1/plants/catalpa-brevipes",
      "self": "/api/v1/species/catalpa-brevipes"
    },
    "rank": "species",
    "scientific_name": "Catalpa brevipes",
    "slug": "catalpa-brevipes",
    "status": "accepted",
    "synonyms": [
      "Catalpa brevipes var. oblongata",
      "Catalpa ekmaniana",
      "Catalpa brevipes subsp. oblongata",
      "Catalpa brevipes subsp. ekmaniana",
      "Catalpa brevipes var. ekmaniana",
      "Catalpa oblongata"
    ],
    "year": 1927
  },
  {
    "author": "(Lam.) DC.",
    "bibliography": "Prodr. 9: 213 (1845)",
    "common_name": null,
    "family": "Bignoniaceae",
    "family_common_name": null,
    "genus": "Tabebuia",
    "genus_id": 10197,
    "id": 209526,
    "image_url": "https://bs.plantnet.org/image/o/58d120a499ed06a574c2d0451db7e72c2f86657e",
    "links": {
      "genus": "/api/v1/genus/tabebuia",
      "plant": "/api/v1/plants/tabebuia-cassinoides",
      "self": "/api/v1/species/tabebuia-cassinoides"
    },
    "rank": "species",
    "scientific_name": "Tabebuia cassinoides",
    "slug": "tabebuia-cassinoides",
    "status": "accepted",
    "synonyms": [
      "Tabebuia magnolioides",
      "Proterpia obtusifolia",
      "Spathodea magnolioides",
      "Catalpa cassinoides",
      "Bignonia cassinoides",
      "Bignonia obtusifolia",
      "Bignonia tabebuya",
      "Bignonia uliginosa",
      "Tecoma uliginosa",
      "Tabebuia uliginosa"
    ],
    "year": 1845
  },
  {
    "author": "(Lam.) Urb.",
    "bibliography": "Symb. Antill. 5: 496 (1908)",
    "common_name": null,
    "family": "Bignoniaceae",
    "family_common_name": null,
    "genus": "Tabebuia",
    "genus_id": 10197,
    "id": 209602,
    "image_url": null,
    "links": {
      "genus": "/api/v1/genus/tabebuia",
      "plant": "/api/v1/plants/tabebuia-microphylla",
      "self": "/api/v1/species/tabebuia-microphylla"
    },
    "rank": "species",
    "scientific_name": "Tabebuia microphylla",
    "slug": "tabebuia-microphylla",
    "status": "accepted",
    "synonyms": [
      "Bignonia microphylla",
      "Catalpa microphylla",
      "Tabebuia truncata",
      "Tabebuia libanensis",
      "Tecoma microphylla",
      "Tabebuia ostenfeldii"
    ],
    "year": 1908
  },
  {
    "author": "L.",
    "bibliography": "Mant. Pl.: 128 (1767)",
    "common_name": "Indian-almond",
    "family": "Combretaceae",
    "family_common_name": null,
    "genus": "Terminalia",
    "genus_id": 5388,
    "id": 107373,
    "image_url": "https://bs.plantnet.org/image/o/97f59bf13d77885e749558d5e362b687ba3294d3",
    "links": {
      "genus": "/api/v1/genus/terminalia",
      "plant": "/api/v1/plants/terminalia-catappa",
      "self": "/api/v1/species/terminalia-catappa"
    },
    "rank": "species",
    "scientific_name": "Terminalia catappa",
    "slug": "terminalia-catappa",
    "status": "accepted",
    "synonyms": [
      "Phytolacca javanica",
      "Terminalia catappa var. pubescens",
      "Myrobalanus catappa",
      "Myrobalanus commersonii",
      "Terminalia catappa var. rhodocarpa",
      "Terminalia catappa var. chlorocarpa",
      "Buceras catappa",
      "Terminalia catappa var. subcordata",
      "Terminalia paraensis",
      "Myrobalanus rubrigemmis",
      "Terminalia rubrigemmis",
      "Juglans catappa",
      "Terminalia latifolia",
      "Terminalia moluccana",
      "Terminalia intermedia",
      "Terminalia kydiana",
      "Terminalia mauritiana",
      "Terminalia catappa var. macrocarpa",
      "Terminalia burmanica",
      "Terminalia ovatifolia",
      "Terminalia subcordata"
    ],
    "year": 1767
  },
  {
    "author": "Griseb.",
    "bibliography": "Cat. Pl. Cub.: 192 (1866)",
    "common_name": null,
    "family": "Bignoniaceae",
    "family_common_name": null,
    "genus": "Catalpa",
    "genus_id": 10217,
    "id": 209792,
    "image_url": null,
    "links": {
      "genus": "/api/v1/genus/catalpa",
      "plant": "/api/v1/plants/catalpa-purpurea",
      "self": "/api/v1/species/catalpa-purpurea"
    },
    "rank": "species",
    "scientific_name": "Catalpa purpurea",
    "slug": "catalpa-purpurea",
    "status": "accepted",
    "synonyms": [
      "Catalpa denticulata",
      "Macrocatalpa purpurea",
      "Catalpa purpurea f. denticulata"
    ],
    "year": 1866
  },
  {
    "author": "Carrière",
    "bibliography": "Revue Horticole 1869: 460. 1869. (Rev. Hort.)",
    "common_name": null,
    "family": "Bignoniaceae",
    "family_common_name": null,
    "genus": "Catalpa",
    "genus_id": 10217,
    "id": 462837,
    "image_url": null,
    "links": {
      "genus": "/api/v1/genus/catalpa",
      "plant": "/api/v1/plants/catalpa-x-erubescens",
      "self": "/api/v1/species/catalpa-x-erubescens"
    },
    "rank": "hybrid",
    "scientific_name": "Catalpa × erubescens",
    "slug": "catalpa-x-erubescens",
    "status": null,
    "synonyms": [],
    "year": null
  },
  {
    "author": "Q.W. Yao & P.C. Huang",
    "bibliography": "Nanjing Techn. Coll. Forest. Prod. 1980(1): 123. 1980. (Nanjing Techn. Coll. Forest. Prod.)",
    "common_name": null,
    "family": "Bignoniaceae",
    "family_common_name": null,
    "genus": "Catalpa",
    "genus_id": 10217,
    "id": 462839,
    "image_url": null,
    "links": {
      "genus": "/api/v1/genus/catalpa",
      "plant": "/api/v1/plants/catalpa-sect-sinoca",
      "self": "/api/v1/species/catalpa-sect-sinoca"
    },
    "rank": "species",
    "scientific_name": "Catalpa sect. Sinoca",
    "slug": "catalpa-sect-sinoca",
    "status": null,
    "synonyms": [],
    "year": null
  },
  {
    "author": "G.Mey.",
    "bibliography": "Prim. Fl. Esseq.: 177 (1818)",
    "common_name": null,
    "family": "Combretaceae",
    "family_common_name": null,
    "genus": "Terminalia",
    "genus_id": 5388,
    "id": 107771,
    "image_url": "https://bs.plantnet.org/image/o/a3eda4ba00a45211bc13747e34af2efe8d95e9cb",
    "links": {
      "genus": "/api/v1/genus/terminalia",
      "plant": "/api/v1/plants/terminalia-dichotoma",
      "self": "/api/v1/species/terminalia-dichotoma"
    },
    "rank": "species",
    "scientific_name": "Terminalia dichotoma",
    "slug": "terminalia-dichotoma",
    "status": "accepted",
    "synonyms": [
      "Tanibouca guianensis",
      "Myrobalanus guianensis",
      "Terminalia tanibouca",
      "Terminalia eriantha",
      "Catappa guyanensis"
    ],
    "year": 1818
  },
  {
    "author": "DC.",
    "bibliography": "Prodr. 3: 11 (1828)",
    "common_name": null,
    "family": "Combretaceae",
    "family_common_name": null,
    "genus": "Terminalia",
    "genus_id": 5388,
    "id": 107760,
    "image_url": "https://d2seqvvyy3b8p2.cloudfront.net/5161b5e498b31d108ab21dd2b9c31eaa.jpg",
    "links": {
      "genus": "/api/v1/genus/terminalia",
      "plant": "/api/v1/plants/terminalia-januarensis",
      "self": "/api/v1/species/terminalia-januarensis"
    },
    "rank": "species",
    "scientific_name": "Terminalia januarensis",
    "slug": "terminalia-januarensis",
    "status": "accepted",
    "synonyms": [
      "Terminalia grandialata",
      "Myrobalanus grandialata",
      "Myrobalanus brasiliensis",
      "Catappa brasiliensis",
      "Terminalia macroptera"
    ],
    "year": 1828
  },
  {
    "author": "Kosterm.",
    "bibliography": "Penerbitan Madj. Penget. Indonesia 1: 34 (1959)",
    "common_name": null,
    "family": "Malvaceae",
    "family_common_name": null,
    "genus": "Heritiera",
    "genus_id": 9590,
    "id": 193866,
    "image_url": null,
    "links": {
      "genus": "/api/v1/genus/heritiera",
      "plant": "/api/v1/plants/heritiera-catappa",
      "self": "/api/v1/species/heritiera-catappa"
    },
    "rank": "species",
    "scientific_name": "Heritiera catappa",
    "slug": "heritiera-catappa",
    "status": "accepted",
    "synonyms": [],
    "year": 1959
  },
  {
    "author": "(L.) L.f.",
    "bibliography": "Suppl. Pl.: 434 (1782)",
    "common_name": null,
    "family": "Combretaceae",
    "family_common_name": null,
    "genus": "Terminalia",
    "genus_id": 5388,
    "id": 405319,
    "image_url": null,
    "links": {
      "genus": "/api/v1/genus/terminalia",
      "plant": "/api/v1/plants/terminalia-bentzoe",
      "self": "/api/v1/species/terminalia-bentzoe"
    },
    "rank": "species",
    "scientific_name": "Terminalia bentzoe",
    "slug": "terminalia-bentzoe",
    "status": "accepted",
    "synonyms": [
      "Myrobalanus bentzoe",
      "Croton bentzoe",
      "Catappa bentzoe"
    ],
    "year": 1782
  }
]

export default plants;
